import{all,put}from'./db.js';import{queue,syncNow}from'./sync.js';import{auth,onAuthStateChanged}from'./firebase.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),uid=()=>crypto.randomUUID(),today=()=>new Date().toISOString().slice(0,10);let rows=[],settings={currency:'₪'};
const money=(n,c)=>`${c}${Number(n||0).toLocaleString('ar-EG',{minimumFractionDigits:0,maximumFractionDigits:2})}`;
async function load(){rows=await all('walletTransactions');const s=await all('settings');if(s[0])settings={...settings,...s[0]};}
function stats(c=settings.currency){const r=rows.filter(x=>!x.deleted&&(x.currency||c)===c),inTotal=r.filter(x=>x.type==='income').reduce((n,x)=>n+Number(x.amount),0),outTotal=r.filter(x=>x.type==='expense').reduce((n,x)=>n+Number(x.amount),0);return{inTotal,outTotal,balance:inTotal-outTotal}}
function modal(html){const root=$('#modalRoot');root.innerHTML=`<div class="modal-backdrop wallet-backdrop" id="walletBackdrop"><div class="modal wallet-modal" role="dialog" aria-modal="true">${html}</div></div>`;const back=$('#walletBackdrop');back.addEventListener('click',e=>{if(e.target===back)close()});back.querySelector('.wallet-modal')?.addEventListener('click',e=>e.stopPropagation())}
function close(){const root=$('#modalRoot');if(root)root.innerHTML=''}
async function save(row){await put('walletTransactions',row);if(window.__zimmahUid)await queue('walletTransactions',row.id,'upsert',row);await load();if(navigator.onLine)syncNow().catch(()=>{});renderCard()}
function form(){modal(`<div class="wallet-modal-head"><div><h2>إضافة حركة مالية</h2><div class="muted">سجّل المال الذي دخل أو خرج من محفظتك.</div></div></div><form id="walletForm" class="form-grid"><div class="wallet-type-grid"><label class="wallet-type income"><input type="radio" name="type" value="income" checked><span>＋ دخل</span></label><label class="wallet-type expense"><input type="radio" name="type" value="expense"><span>− مصروف</span></label></div><div class="field"><label>المبلغ<input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" required></label></div><div class="two grid"><div class="field"><label>العملة<select name="currency"><option ${settings.currency==='₪'?'selected':''}>₪</option><option ${settings.currency==='$'?'selected':''}>$</option><option ${settings.currency==='د.أ'?'selected':''}>د.أ</option></select></label></div><div class="field"><label>التاريخ<input name="date" type="date" value="${today()}"></label></div></div><div class="field"><label>الوصف<input name="description" placeholder="مثال: راتب، بنزين، مشتريات..."></label></div><div class="modal-actions"><button type="button" class="btn ghost" id="walletCancel">إلغاء</button><button type="submit" class="btn primary">حفظ الحركة</button></div></form>`);const cancel=$('#walletCancel'),formEl=$('#walletForm');if(cancel)cancel.onclick=e=>{e.preventDefault();e.stopPropagation();close()};if(formEl)formEl.onsubmit=async e=>{e.preventDefault();e.stopPropagation();const d=Object.fromEntries(new FormData(e.target));const row={id:uid(),userId:window.__zimmahUid||'local',type:d.type,amount:Number(d.amount),currency:d.currency,date:d.date||today(),description:d.description||'',createdAt:Date.now(),updatedAt:Date.now(),deleted:false,version:1,syncStatus:'pending'};await save(row);close();toast('تم حفظ الحركة')};setTimeout(()=>$('#walletForm input[name="amount"]')?.focus(),0)}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
function walletModal(){const c=settings.currency,s=stats(c),recent=rows.filter(x=>!x.deleted&&(x.currency||c)===c).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt).slice(0,8);modal(`<div class="wallet-modal-head"><div><h2>أموالي</h2><div class="muted">رصيدك الشخصي، منفصل عن الذمم.</div></div><button type="button" class="btn primary" id="walletAdd">+ حركة</button></div><div class="wallet-balance-card"><div class="muted">الرصيد الحالي · ${esc(c)}</div><div class="wallet-big ${s.balance>=0?'positive':'negative'}">${money(s.balance,c)}</div><div class="wallet-mini"><span>زاد <b class="positive">+${money(s.inTotal,c)}</b></span><span>نقص <b class="negative">-${money(s.outTotal,c)}</b></span></div></div><div class="wallet-stats grid"><div class="card"><div class="muted">إجمالي الداخل</div><b class="positive">+${money(s.inTotal,c)}</b></div><div class="card"><div class="muted">إجمالي الخارج</div><b class="negative">-${money(s.outTotal,c)}</b></div></div><div class="section"><div class="section-head"><h3>آخر الحركات</h3></div><div class="list">${recent.length?recent.map(x=>`<div class="card tx-row"><div><b>${x.type==='income'?'دخل':'مصروف'}</b><div class="muted">${esc(x.description||'بدون وصف')} · ${esc(x.date)}</div></div><span class="amount ${x.type==='income'?'positive':'negative'}">${x.type==='income'?'+':'-'}${money(x.amount,x.currency)}</span></div>`).join(''):'<div class="card empty">أضف أول حركة مالية لتبدأ تتبع رصيدك.</div>'}</div></div>`);$('#walletAdd').onclick=e=>{e.preventDefault();e.stopPropagation();form()}}
function renderCard(){const host=$('#walletWidget');if(!host)return;const c=settings.currency,s=stats(c);host.innerHTML=`<div class="wallet-card card"><div class="wallet-card-top"><div><div class="muted">أموالي</div><div class="wallet-card-balance">${money(s.balance,c)}</div></div><button type="button" class="btn ghost wallet-open">عرض التفاصيل</button></div><div class="wallet-flow"><span><i class="wallet-dot in"></i> زاد <b class="positive">+${money(s.inTotal,c)}</b></span><span><i class="wallet-dot out"></i> نقص <b class="negative">-${money(s.outTotal,c)}</b></span></div><button type="button" class="btn primary wallet-add">+ إضافة حركة</button></div>`;host.querySelector('.wallet-open').onclick=e=>{e.preventDefault();e.stopPropagation();walletModal()};host.querySelector('.wallet-add').onclick=e=>{e.preventDefault();e.stopPropagation();form()}}
function inject(){const content=$('#content');if(!content)return;const isDash=content.querySelector('.page-title')?.textContent?.includes('مرحبًا');if(!isDash){document.querySelector('#walletWidget')?.remove();return}let host=$('#walletWidget');if(!host){host=document.createElement('section');host.id='walletWidget';host.className='section';const first=content.querySelector('.stats');if(first)first.insertAdjacentElement('afterend',host);else content.prepend(host)}renderCard()}
const observer=new MutationObserver(()=>{clearTimeout(window.__walletRenderTimer);window.__walletRenderTimer=setTimeout(inject,30)});const content=$('#content');if(content)observer.observe(content,{childList:true,subtree:true});
window.__zimmahUid=null;if(auth)onAuthStateChanged(auth,user=>{window.__zimmahUid=user?.uid||null;load().then(inject)});load().then(inject);window.walletOpen=walletModal;
