import{all,put}from'./db.js';import{queue,syncNow}from'./sync.js';import{auth,onAuthStateChanged}from'./firebase.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),uid=()=>crypto.randomUUID(),today=()=>new Date().toISOString().slice(0,10);let accounts=[],rows=[],settings={currency:'₪'};
async function load(){accounts=await all('walletAccounts');rows=await all('walletTransactions');const s=await all('settings');if(s[0])settings={...settings,...s[0]};await migrateLegacy();accounts=await all('walletAccounts');rows=await all('walletTransactions')}
async function migrateLegacy(){if(accounts.length||!rows.length)return;const a={id:uid(),userId:window.__zimmahUid||'local',name:'مصاريي',icon:'👤',createdAt:Date.now(),updatedAt:Date.now(),deleted:false};await put('walletAccounts',a);await queue('walletAccounts',a.id,'upsert',a).catch(()=>{});for(const old of rows){const x={...old,walletId:a.id,owner:'me'};await put('walletTransactions',x)} }
function activeAccounts(){return accounts.filter(a=>!a.deleted)}
function balance(id,c=settings.currency){return rows.filter(x=>!x.deleted&&(x.currency||c)===c).reduce((n,x)=>{if(x.type==='transfer')return n+(x.toWalletId===id?Number(x.amount):x.fromWalletId===id?-Number(x.amount):0);return x.walletId===id?(n+(x.type==='income'?1:-1)*Number(x.amount)):n},0)}
function totals(c=settings.currency){const a=activeAccounts();let total=0;for(const x of a)total+=balance(x.id,c);return{total,accounts:a.map(w=>({...w,balance:balance(w.id,c)}))}}
const money=(n,c)=>`${c}${Number(n||0).toLocaleString('ar-EG',{minimumFractionDigits:0,maximumFractionDigits:2})}`;
function modal(html){const root=$('#modalRoot');if(!root)return;root.innerHTML=`<div class="modal-backdrop wallet-backdrop" id="walletBackdrop"><div class="modal wallet-modal" role="dialog" aria-modal="true">${html}</div></div>`;const back=$('#walletBackdrop');back.addEventListener('click',e=>{if(e.target===back)close()});back.querySelector('.wallet-modal')?.addEventListener('click',e=>e.stopPropagation())}
function close(){const root=$('#modalRoot');if(root)root.innerHTML=''}
async function save(store,row){await put(store,row);if(window.__zimmahUid)await queue(store,row.id,'upsert',row);await load();if(navigator.onLine)syncNow().catch(()=>{});renderCard()}
function accountForm(){modal(`<div class="wallet-modal-head"><div><h2>محفظة جديدة</h2><div class="muted">مثلاً: الدار، أخوي، عمتي.</div></div></div><form id="walletAccountForm" class="form-grid"><div class="field"><label>اسم المحفظة<input name="name" placeholder="مثال: مصاري الدار" required></label></div><div class="field"><label>رمز <input name="icon" value="👤" maxlength="2"></label></div><div class="modal-actions"><button type="button" class="btn ghost" id="walletCancel">إلغاء</button><button class="btn primary">حفظ</button></div></form>`);$('#walletCancel').onclick=close;$('#walletAccountForm').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const a={id:uid(),userId:window.__zimmahUid||'local',name:d.name.trim(),icon:d.icon||'👤',createdAt:Date.now(),updatedAt:Date.now(),deleted:false};await save('walletAccounts',a);close();toast('تمت إضافة المحفظة')}}
function movementForm(){const opts=activeAccounts().map(a=>`<option value="${a.id}">${esc(a.icon||'👤')} ${esc(a.name)}</option>`).join('');modal(`<div class="wallet-modal-head"><div><h2>إضافة حركة</h2><div class="muted">اختار شو صار، والتطبيق يحسب الأرصدة لحاله.</div></div></div><form id="walletMoveForm" class="form-grid"><div class="wallet-type-grid"><label class="wallet-type income"><input type="radio" name="type" value="income" checked><span>＋ دخل</span></label><label class="wallet-type expense"><input type="radio" name="type" value="expense"><span>− مصروف</span></label><label class="wallet-type transfer"><input type="radio" name="type" value="transfer"><span>↔ تحويل</span></label></div><div class="field"><label>المحفظة<select name="walletId">${opts}</select></label></div><div class="field transfer-only" hidden><label>تحويل إلى<select name="toWalletId">${opts}</select></label></div><div class="two grid"><div class="field"><label>المبلغ<input name="amount" type="number" min="0.01" step="0.01" inputmode="decimal" required></label></div><div class="field"><label>العملة<select name="currency"><option ${settings.currency==='₪'?'selected':''}>₪</option><option ${settings.currency==='$'?'selected':''}>$</option><option ${settings.currency==='د.أ'?'selected':''}>د.أ</option></select></label></div></div><div class="two grid"><div class="field"><label>التاريخ<input name="date" type="date" value="${today()}"></label></div><div class="field"><label>الوصف<input name="description" placeholder="مثال: شرية، راتب، فاتورة..."></label></div></div><div class="modal-actions"><button type="button" class="btn ghost" id="walletCancel">إلغاء</button><button class="btn primary">حفظ الحركة</button></div></form>`);const f=$('#walletMoveForm'),typeEls=f.querySelectorAll('input[name=type]'),transfer=f.querySelector('.transfer-only'),wallet=f.querySelector('[name=walletId]'),to=f.querySelector('[name=toWalletId]');const toggle=()=>{const is=f.querySelector('input[name=type]:checked').value==='transfer';transfer.hidden=!is;if(is&&to.value===wallet.value){const other=[...to.options].find(o=>o.value!==wallet.value);if(other)to.value=other.value}};typeEls.forEach(x=>x.onchange=toggle);wallet.onchange=toggle;f.querySelector('#walletCancel').onclick=close;f.onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f)),now=Date.now(),amount=Number(d.amount);if(!amount||amount<=0)return toast('أدخل مبلغًا صحيحًا');if(d.type==='transfer'&&d.walletId===d.toWalletId)return toast('اختار محفظتين مختلفتين');const row={id:uid(),userId:window.__zimmahUid||'local',type:d.type,amount,currency:d.currency,walletId:d.walletId,fromWalletId:d.type==='transfer'?d.walletId:'',toWalletId:d.type==='transfer'?d.toWalletId:'',date:d.date||today(),description:d.description||'',createdAt:now,updatedAt:now,deleted:false,version:1,syncStatus:'pending'};await save('walletTransactions',row);close();toast('تم حفظ الحركة')}}
function walletDetails(id){const a=activeAccounts().find(x=>x.id===id);if(!a)return;const c=settings.currency,list=rows.filter(x=>!x.deleted&&(x.currency||c)===c&&(x.walletId===id||x.fromWalletId===id||x.toWalletId===id)).sort((x,y)=>y.date.localeCompare(x.date)||y.createdAt-x.createdAt).slice(0,20);modal(`<div class="wallet-modal-head"><div><h2>${esc(a.icon||'👤')} ${esc(a.name)}</h2><div class="wallet-big ${balance(id,c)>=0?'positive':'negative'}">${money(balance(id,c),c)}</div></div><button type="button" class="btn primary" id="walletAdd">+ حركة</button></div><div class="section"><div class="muted">آخر الحركات</div><div class="list">${list.length?list.map(x=>{const isIn=x.type==='income'?true:x.type==='expense'?false:x.toWalletId===id;const other=x.type==='transfer'?(isIn?activeAccounts().find(z=>z.id===x.fromWalletId)?.name:activeAccounts().find(z=>z.id===x.toWalletId)?.name):'';return `<div class="card tx-row"><div><b>${x.type==='transfer'?'تحويل':x.type==='income'?'دخل':'مصروف'}</b><div class="muted">${esc(x.description||other||'بدون وصف')} · ${esc(x.date)}</div></div><span class="amount ${isIn?'positive':'negative'}">${isIn?'+':'-'}${money(x.amount,x.currency)}</span></div>`}).join(''):'<div class="card empty">لا توجد حركات بعد.</div>'}</div></div>`);$('#walletAdd').onclick=movementForm}
function walletModal(){const t=totals(),c=settings.currency;modal(`<div class="wallet-modal-head"><div><h2>أموالي</h2><div class="muted">كل محفظة تمثل مصاري مين، بدون خلطها مع الديون.</div></div><button type="button" class="btn primary" id="walletNew">+ محفظة</button></div><div class="wallet-balance-card"><div class="muted">إجمالي المصاري الموجودة</div><div class="wallet-big ${t.total>=0?'positive':'negative'}">${money(t.total,c)}</div><div class="muted">${esc(c)} · مجموع المحافظ الحالية</div></div><div class="wallet-account-grid">${t.accounts.map(a=>`<button type="button" class="card wallet-account" data-wallet="${a.id}"><span class="wallet-account-icon">${esc(a.icon||'👤')}</span><span class="wallet-account-name">${esc(a.name)}</span><strong class="${a.balance>=0?'positive':'negative'}">${money(a.balance,c)}</strong></button>`).join('')}</div><div class="modal-actions"><button type="button" class="btn primary" id="walletMove">+ إضافة حركة</button></div>`);$('#walletNew').onclick=accountForm;$('#walletMove').onclick=movementForm;document.querySelectorAll('[data-wallet]').forEach(b=>b.onclick=()=>walletDetails(b.dataset.wallet))}
function renderCard(){const host=$('#walletWidget');if(!host)return;host.hidden=false;host.style.display='block';host.style.visibility='visible';host.style.opacity='1';const t=totals(),c=settings.currency;host.innerHTML=`<div class="wallet-card card"><div class="wallet-card-top"><div><div class="muted">أموالي</div><div class="wallet-card-balance">${money(t.total,c)}</div></div><button type="button" class="btn ghost wallet-open">المحافظ</button></div><div class="wallet-accounts-preview">${t.accounts.slice(0,4).map(a=>`<div class="wallet-preview-row"><span>${esc(a.icon||'👤')} ${esc(a.name)}</span><b class="${a.balance>=0?'positive':'negative'}">${money(a.balance,c)}</b></div>`).join('')||'<div class="muted">أضف أول محفظة لتبدأ.</div>'}</div><button type="button" class="btn primary wallet-add">+ إضافة حركة</button></div>`;host.querySelector('.wallet-open').onclick=e=>{e.preventDefault();e.stopPropagation();walletModal()};host.querySelector('.wallet-add').onclick=e=>{e.preventDefault();e.stopPropagation();if(!activeAccounts().length)accountForm();else movementForm()}}
function inject(){const content=$('#content');if(!content)return;const title=content.querySelector('.page-title')?.textContent?.trim()||'';const dashboard=title.includes('مرحبًا')||title.includes('ذِمّة');let host=$('#walletWidget');if(!dashboard){if(host)host.remove();return}if(!host){host=document.createElement('section');host.id='walletWidget';host.className='section wallet-widget';host.setAttribute('aria-label','أموالي');const statsEl=content.querySelector('.stats');if(statsEl)statsEl.insertAdjacentElement('afterend',host);else content.prepend(host)}renderCard()}
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
function boot(){load().then(inject);const content=$('#content');if(content)new MutationObserver(()=>{clearTimeout(window.__walletRenderTimer);window.__walletRenderTimer=setTimeout(inject,30)}).observe(content,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
if(auth)onAuthStateChanged(auth,user=>{window.__zimmahUid=user?.uid||null;load().then(inject)});else window.__zimmahUid=null;window.walletOpen=walletModal;
